#ifndef MENSAJES_H
#define MENSAJES_H

#include <Arduino.h>

const String mensajes[] = {
    "Cree en ti mismo, siempre.",
    "El éxito comienza con un sueño.",
    "Persigue tus sueños, no te rindas.",
    "Hazlo con pasión o no lo hagas.",
    "Cada día es una nueva oportunidad.",
    "Sé la mejor versión de ti.",
    "Nunca es tarde para empezar.",
    "La actitud lo es todo.",
    "Confía en tu viaje.",
    "Sigue adelante, sin miedo.",
    "La persistencia supera la resistencia.",
    "El cambio empieza en ti.",
    "Hazlo ahora, el futuro es incierto.",
    "La clave está en no rendirse.",
    "Eres más fuerte de lo que crees.",
    "Sigue tus sueños, siempre.",
    "La acción trae resultados.",
    "Cree que puedes y lo lograrás.",
    "Cada día es una nueva oportunidad.",
    "Tu potencial es ilimitado.",
    "Aprovecha cada momento.",
    "La perseverancia vence todo.",
    "Sé valiente, sé fuerte.",
    "No te rindas jamás.",
    "El esfuerzo trae recompensas.",
    "Sigue adelante, siempre.",
    "Tú eres tu única limitación.",
    "Cree en tus capacidades.",
    "Haz que cada día cuente.",
    "El éxito es una elección.",
    "Nunca dejes de soñar.",
    "El esfuerzo es la clave.",
    "Todo es posible.",
    "La fe mueve montañas.",
    "La disciplina trae éxito.",
    "Confía en el proceso.",
    "Atrévete a ser diferente.",
    "Nunca te rindas.",
    "Lo mejor está por venir.",
    "Siempre adelante.",
    "Sé imparable.",
    "Vive sin límites.",
    "Hazlo con pasión.",
    "Sigue soñando.",
    "Actúa ahora.",
    "Sé valiente.",
    "Eres capaz.",
    "Sueña en grande.",
    "Sigue luchando.",
    "Confía en ti."
};

#endif